### ISSUE TITLE
Error in `generated-tls-issuer-staging.yaml` when used with Cloudflare DNS Service

### ISSUE THREAD

**Issue by cellerich** [openfaas-incubator/ofc-bootstrap#165]
When running ofc_boostrap with **Cloudflare** as the DNS Service and the **issuer_type: "staging"** the file **generated-tls-issuer-staging.yml** is missing the section about the Cloudflare entities

## Expected Behaviour
The file should look like this:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: openfaas
spec:
  acme:
    email: "my@email.com"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: my@email.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
```

## Current Behaviour
The generated file looks like that:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: openfaas
spec:
  acme:
    email: "my@email.com"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
```

## Steps to Reproduce (for bugs)
run **ofc_bootstrap** with the following entries in the **init.yaml** file:
```yaml
#TLS config section
tls: true
tls_config:
  # issuer_type: "prod"
  issuer_type: "staging"
  email: "my@email.com"
  #Cloudflare
  dns_service: cloudflare

  # Cloudflare - Secrets section
secrets:
  - name: "cloudflare-api-key-secret"
    literals:
      - name: "api-key"
        value: "apikeyredacted"

```

## Context
Trying to install openfaas cloud on a k3s cluster

## Your Environment

* `faas-cli version` ( full output ):
```bash
faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  0ab4012784510381e2b90c031ede3d77197b10b1
 version: 0.11.0
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```bash
docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```
* Kubernetes version `kubectl version`:
```bash
kubectl version                                                                              1 ↵ Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10

**Comment by alexellis** [comment]
Do you want to work on a fix for it? There's a unit test that matched the Jetstack documentation. Do you think it may be wrong?

**Comment by cellerich** [comment]
Just found the Error in the file `templates/k8s/tls/issuer-staging.yml` 

this would be the fix:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: openfaas
spec:
  acme:
    email: "{{.Email}}"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        {{.DNSService}}:
          {{ if eq .DNSService "clouddns" }}
          project: "{{.ProjectID}}"
          serviceAccountSecretRef:
            name: "{{.DNSService}}-service-account"
            key: service-account.json
          {{else if eq .DNSService "route53" }}
          region: {{.Region}}
          # optional if ambient credentials are available; see ambient credentials documentation
          accessKeyID: {{.AccessKeyID}}
          secretAccessKeySecretRef:
            name: "{{.DNSService}}-credentials-secret"
            key: secret-access-key
          {{else if eq .DNSService "cloudflare" }}
          email: {{.Email}}
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
          {{else if eq .DNSService "digitalocean" }}
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
          {{ end }}
```

The section ` {{else if eq .DNSService "cloudflare" }}` is missing there.

Sorry, never did a Pull Request on a Open Source Project. Might go into it later on this or next year.
But I hope the pointer helps as well.
