### ISSUE TITLE
Remove OAuth client_secret config duplication

### ISSUE THREAD

**Issue by ivanayov** [openfaas-incubator/ofc-bootstrap#36]
At the moment it's configured in two places: 
```
 - name: "of-client-secret"
    literals:
      - name: of-client-secret
        value: "fdshdg2be27e9h67shg9774nfsf89fnbksb0"
    namespace: "openfaas"
```
and second time in
```
oauth:
  client_id: 786sdfhg9bgb0bgsbj9
  client_secret: fdshdg2be27e9h67shg9774nfsf89fnbksb0
```

One possible solution is to add `value_from_config` option for the secrets and update `CreateK8sSecret()`
