### ISSUE TITLE
Only create the secrets we need for the user's configuration

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#59]
## Expected Behaviour

We should only create the secrets we need for the user's configuration.

## Current Behaviour

We either comment out secrets we don't want or need, or we create them even when we don't need them.

Example: if auth is turned off we should create `of-client-secret` in the cluster.

## Possible Solution

On call with Bart and Ivana, we thought we could detect features enabled from `init.yaml` such as:

```yaml
features:
- scm_github
- scm_gitlab
- tls
- auth
- route53_dns01
- gcp_dns01
- do_dns01
- kubernetes
- swarm
```

Then go on to filter the secrets based upon the list.

The secrets may need a `filter` to say which features they are enabled for.

```yaml
  - name: "github-webhook-secret"
    literals:
      - name: "github-webhook-secret"
        value: ""
    namespace: "openfaas-fn"
    filter:
     - github
```

**Comment by martindekov** [comment]
I can tackle this

**Comment by martindekov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Hi Martin when are you planning to work on this? Are you ok for other people to collaborate?

**Comment by martindekov** [comment]
I will ask in the Issue, I thought this features thing is about the secret creation only. I was wondering are all those features configured in the `init.yml`. In other words I see `gcp_dns01`  `do_dns01` which I think serve one purpose but with different providers. I see by default `do_dns01` configured here 
```  
- name: "digitalocean-dns"
    files:
      - name: "access-token"
        value_from: "~/Downloads/do-access-token"
    filters:
      - "9"
    namespace: "cert-manager"
``` 
But I don't see equivalence for google cloud platform in `init.yml`. Also the GitLab feature is in [this PR](https://github.com/openfaas-incubator/ofc-bootstrap/pull/46/files). Also is the kubernetes configuration the same as docker swarm one. I see it is configured for kubernetes by default. Should I implement the logic only(determine if block in `init.yml` is `feature`) and those things (`gitlab`,`swarm`,`gce-dns`) be added later ?

**Comment by martindekov** [comment]
Otherwise the secrets filtering is implemented, In the PR above. But the filters I named 1,2,3, ... this is something with which I can get some help. ATM the filtering happens list - list aka. one secret can have multiple features.

**Comment by alexellis** [comment]
Just to be clear I would not expect a user to see inside init.yaml:

```
features:
- scm_github
- scm_gitlab
- tls
- auth
- route53_dns01
- gcp_dns01
- do_dns01
- kubernetes
- swarm
```

I am merely listing off the features I think we have right now and need.

We can derive what features are enabled based upon what is set by the user in the code.

**Comment by alexellis** [comment]
I'd expect secrets to look like:

```
- name: "digitalocean-dns"
    files:
      - name: "access-token"
        value_from: "~/Downloads/do-access-token"
    namespace: "cert-manager"
    filters:
      - "do_dns01"
      - "tls"
```
