### ISSUE TITLE
Feature: create pull secret for Kubernetes

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#80]
## Expected Behaviour

If using a private remote registry we should create a pull secret in the cluster when using Kubernetes.

## Current Behaviour

When using the Docker Hub we generally auth for pushing, but don't auth for pulling because we use public images. With a private registry users need to add a "pull secret" afterwards. https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes

## Possible Solution

Can we parse the `docker/config.json` file, find the server entry needed and then create the secret programatically from the one which has already been provided?

https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes

**Comment by alexellis** [comment]
cc @kamaln7

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by viveksyngh** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials

**Comment by alexellis** [comment]
Looks useful.

**Comment by viveksyngh** [comment]
@alexellis 

I was trying to achieve this in my kubernetes cluster. I was able to create a secret using above kubernetes documentation and pull private images.  

But secrets for functions in openfaas cloud  should have name prefixed with github `username`. How are we going to create the secrets for each user ?

**Comment by zeerorg** [comment]
Openfaas cloud pushes all the images to a single registry so we only need a single Pull secret for all users

**Comment by zeerorg** [comment]
So only your first paragraph is the goal :-)

**Comment by viveksyngh** [comment]
Let me explain 2nd paragraph with example. 

So suppose we created a secret with name `pull-secret` using docker config in `openfaas-fn` namespace. 

Now to use that secret with every function we need to pass that secret in `secrets` for each function. 
```
 ...
 secrets:
   - pull-secret
```

What I noticed, when openfaas-cloud deploys that function it looks for `githubusername-pull-secret` in my case `viveksyngh-pull-secret`. How do we fix that? I there something I am missing ?

**Comment by zeerorg** [comment]
Please take a look at https://docs.openfaas.com/deployment/kubernetes/#option-2-link-an-image-pull-secret-to-the-namespaces-serviceaccount
So we need to define this during the kubernetes deploy

**Comment by viveksyngh** [comment]
Got it .. thanks for pointing. Still learning kubernetes :)

**Comment by viveksyngh** [comment]
I was thinking for this approach for this. Let me know your thought.

Create `openfaas-fn` name space. 

We will create a secret with name `pull-secret` using `config.json`
```
kubectl create secret generic pull-secret  --from-file=.dockerconfigjson=~/.docker/config.json     --type=kubernetes.io/dockerconfigjson -n openfaas-fn
```

Then update the serviceaccount of `openfaas-fn`  and add `pull-secret` to it.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: openfaas-fn
secrets:
- name: pull-secret
```

**Comment by kamaln7** [comment]
Nice job @viveksyngh! I think we can consolidate the two registry secrets into one. So take [this existing secret](https://github.com/openfaas-incubator/ofc-bootstrap/blob/e4fa99ca0d9ed3c419671b8e719f45e46876250c/example.init.yaml#L83-L87) and add `.dockerconfigjson` to it. I haven't tried this but I believe this will work:

```
      - name: "config.json"
        value_from: "~/.docker/config.json"
      - name: ".dockerconfigjson"
        value_from: "~/.docker/config.json"
```

We'd still need to add it to the service account like you said

**Comment by viveksyngh** [comment]
@kamaln7  thanks for suggestion. Only challenge I see here is one needs to be created for `openfaas` namespace and other needs to be created `openfaas-fn` namespace.  We can pass only one namespace for a secret in the config.

**Comment by kamaln7** [comment]
Ah, right. So maybe something like this:

```yaml
  - name: "registry-secret"
    files:
      - name: "config.json"
        value_from: "~/.docker/config.json"
    namespace: "openfaas"
  - name: "registry-secret"
    files:
      - name: ".dockerconfigjson"
        value_from: "~/.docker/config.json"
        type: "kubernetes.io/dockerconfigjson"
    namespace: "openfaas-fn"
```

But you'd need support for the secret `type` here https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/pkg/types/secrets.go#L22
